"sdr_preservationIngestWF_transfer-object,sdr_preservationIngestWF_validate-bag,sdr_preservationIngestWF_verify-apo,sdr_preservationIngestWF_update-moab,sdr_preservationIngestWF_update-catalog,sdr_preservationIngestWF_complete-ingest": 10
